# Generated by Django 6.0.1 on 2026-01-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('link', models.CharField()),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField()),
                ('time_created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='lexable.collection')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unlocks', to='lexable.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('part_of_speech', models.CharField()),
                ('citation_form', models.CharField()),
                ('pronunciation', models.CharField()),
                ('metadata', models.JSONField()),
                ('image', models.CharField(blank=True)),
                ('add_by_default', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_lexemes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LexemeAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_flashcards', models.BooleanField()),
                ('locale_date_created', models.DateField()),
                ('time_created', models.DateTimeField()),
                ('time_updated', models.DateTimeField()),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lexeme_adds', to='lexable.lexeme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lexeme_adds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardDueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_type', models.CharField(choices=[('citation_form', 'citation form'), ('definition', 'definition'), ('cloze', 'cloze'), ('pronunciation', 'pronunciation'), ('metadata', 'metadata')])),
                ('metadata_field', models.CharField()),
                ('due_date', models.DateField()),
                ('lexeme_add', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='due_dates', to='lexable.lexemeadd')),
            ],
        ),
        migrations.CreateModel(
            name='LexemeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField()),
                ('language', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('num_occurrences', models.IntegerField()),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='lexable.lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='LexemeSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senses', to='lexable.lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('text', models.CharField()),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='lexable.lexemesense')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='lexable.document')),
            ],
        ),
        migrations.CreateModel(
            name='SectionAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_day_created', models.DateField()),
                ('time_created', models.DateTimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_adds', to='lexable.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_adds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('sentence_type', models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('np', 'new paragraph'), ('npi', 'new block-indented paragraph'), ('p', 'paragraph continued'), ('hr', 'horizontal rule'), ('img', 'image')])),
                ('text', models.TextField()),
                ('formatting', models.JSONField()),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='lexable.section')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('text', models.TextField()),
                ('formatting', models.JSONField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='lexable.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistoryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('language', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('words_read', models.IntegerField()),
                ('lexemes_added', models.IntegerField()),
                ('cards_played', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_from', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('currently_learning', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('ask_difficulty', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordInSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_in_trials', models.BooleanField()),
                ('lexeme_sense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='words', to='lexable.lexemesense')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='words', to='lexable.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_date_created', models.DateField()),
                ('time_created', models.DateTimeField()),
                ('trial_type', models.CharField(choices=[('citation_form', 'citation form'), ('definition', 'definition'), ('cloze', 'cloze'), ('pronunciation', 'pronunciation'), ('metadata', 'metadata')])),
                ('metadata_field', models.CharField(blank=True)),
                ('choices', models.CharField()),
                ('difficulty', models.CharField(choices=[('incorrect', 'incorrect'), ('difficult', 'difficult'), ('moderate', 'moderate'), ('easy', 'easy')])),
                ('lexeme_add', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='lexable.lexemeadd')),
                ('cloze_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='lexable.wordinsentence')),
            ],
        ),
        migrations.CreateModel(
            name='Substring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substrings', to='lexable.wordinsentence')),
            ],
        ),
        migrations.CreateModel(
            name='WordListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wordlist_inclusions', to='lexable.lexeme')),
                ('wordlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='lexable.wordlist')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTitleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='title_translations', to='lexable.collection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('collection', 'language'), name='unique_title_translation_collection_language')],
            },
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_credit_balance_user')],
            },
        ),
        migrations.CreateModel(
            name='DocumentTitleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('arb', 'Arabic'), ('cmn', 'Mandarin'), ('deu', 'German'), ('eng', 'English'), ('epo', 'Esperanto'), ('fra', 'French'), ('heb', 'Hebrew'), ('hin', 'Hindi'), ('ita', 'Italian'), ('jpn', 'Japanese'), ('kor', 'Korean'), ('nld', 'Dutch'), ('por', 'Portuguese'), ('rus', 'Russian'), ('spa', 'Spanish'), ('tur', 'Turkish')])),
                ('title', models.CharField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='title_translations', to='lexable.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'language'), name='unique_title_translation_document_language')],
            },
        ),
        migrations.CreateModel(
            name='Etymology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etymology_type', models.CharField(choices=[('derived', 'derived'), ('contains', 'contains'), ('variant', 'variant')])),
                ('derived_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etymologies', to='lexable.lexeme')),
                ('source_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivations', to='lexable.lexeme')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_lexeme', 'derived_lexeme'), name='unique_etymology')],
            },
        ),
        migrations.AddConstraint(
            model_name='lexemeadd',
            constraint=models.UniqueConstraint(fields=('lexeme', 'user'), name='unique_add_lexeme_user'),
        ),
        migrations.AddConstraint(
            model_name='cardduedate',
            constraint=models.UniqueConstraint(fields=('lexeme_add', 'trial_type'), name='unique_card_due_date'),
        ),
        migrations.AddConstraint(
            model_name='lexemeform',
            constraint=models.UniqueConstraint(fields=('form', 'lexeme'), name='unique_lexeme_form'),
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(fields=('sense', 'language'), name='unique_definition_sense_language'),
        ),
        migrations.AddConstraint(
            model_name='sectionadd',
            constraint=models.UniqueConstraint(fields=('section', 'user'), name='unique_add_section_user'),
        ),
        migrations.AddConstraint(
            model_name='sentencetranslation',
            constraint=models.UniqueConstraint(fields=('sentence', 'language'), name='unique_translation_sentence_language'),
        ),
        migrations.AddConstraint(
            model_name='userhistorydate',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'language'), name='unique_user_history_date'),
        ),
        migrations.AddConstraint(
            model_name='usersettings',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_settings'),
        ),
    ]
