# Generated by Django 6.0.1 on 2026-01-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='author',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='free',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
