# Generated by Django 6.0.1 on 2026-01-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexable', '0002_collection_author_collection_free_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
