# Generated by Django 6.0.1 on 2026-01-29 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexable', '0003_document_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cardduedate',
            name='unique_card_due_date',
        ),
        migrations.AddField(
            model_name='cardduedate',
            name='last_reviewed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cardduedate',
            name='sense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='due_dates', to='lexable.lexemesense'),
        ),
    ]
